# Generated by Django 5.1.7 on 2025-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
